[2022-05-29 08:27:08,834] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: Etl.create_employees_table scheduled__2022-05-27T00:00:00+00:00 [queued]>
[2022-05-29 08:27:08,840] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: Etl.create_employees_table scheduled__2022-05-27T00:00:00+00:00 [queued]>
[2022-05-29 08:27:08,840] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-29 08:27:08,840] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-29 08:27:08,840] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-29 08:27:08,849] {taskinstance.py:1378} INFO - Executing <Task(PostgresOperator): create_employees_table> on 2022-05-27 00:00:00+00:00
[2022-05-29 08:27:08,852] {standard_task_runner.py:52} INFO - Started process 60 to run task
[2022-05-29 08:27:08,854] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Etl', 'create_employees_table', 'scheduled__2022-05-27T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpiy6be8y7', '--error-file', '/tmp/tmpur1hyf5o']
[2022-05-29 08:27:08,854] {standard_task_runner.py:80} INFO - Job 40: Subtask create_employees_table
[2022-05-29 08:27:08,888] {task_command.py:370} INFO - Running <TaskInstance: Etl.create_employees_table scheduled__2022-05-27T00:00:00+00:00 [running]> on host b7bcf2b221fa
[2022-05-29 08:27:08,941] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Etl
AIRFLOW_CTX_TASK_ID=create_employees_table
AIRFLOW_CTX_EXECUTION_DATE=2022-05-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-27T00:00:00+00:00
[2022-05-29 08:27:08,947] {base.py:68} INFO - Using connection ID 'tutorial_pg_conn' for task execution.
[2022-05-29 08:27:08,950] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS employees (
                "Serial Number" NUMERIC PRIMARY KEY,
                "Company Name" TEXT,
                "Employee Markme" TEXT,
                "Description" TEXT,
                "Leave" INTEGER
            );, parameters: None
[2022-05-29 08:27:08,950] {postgres.py:94} INFO - NOTICE:  relation "employees" already exists, skipping

[2022-05-29 08:27:08,960] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=Etl, task_id=create_employees_table, execution_date=20220527T000000, start_date=20220529T082708, end_date=20220529T082708
[2022-05-29 08:27:08,986] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-29 08:27:09,015] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
