[2022-05-27 08:19:09,481] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: Etl.merge_data scheduled__2022-05-26T00:00:00+00:00 [queued]>
[2022-05-27 08:19:09,487] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: Etl.merge_data scheduled__2022-05-26T00:00:00+00:00 [queued]>
[2022-05-27 08:19:09,487] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-05-27 08:19:09,487] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-05-27 08:19:09,487] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-05-27 08:19:09,496] {taskinstance.py:1378} INFO - Executing <Task(_PythonDecoratedOperator): merge_data> on 2022-05-26 00:00:00+00:00
[2022-05-27 08:19:09,498] {standard_task_runner.py:52} INFO - Started process 63 to run task
[2022-05-27 08:19:09,500] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Etl', 'merge_data', 'scheduled__2022-05-26T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpfy78i5z9', '--error-file', '/tmp/tmp_hexogh3']
[2022-05-27 08:19:09,500] {standard_task_runner.py:80} INFO - Job 34: Subtask merge_data
[2022-05-27 08:19:09,530] {task_command.py:370} INFO - Running <TaskInstance: Etl.merge_data scheduled__2022-05-26T00:00:00+00:00 [running]> on host b7bcf2b221fa
[2022-05-27 08:19:09,570] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Etl
AIRFLOW_CTX_TASK_ID=merge_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-26T00:00:00+00:00
[2022-05-27 08:19:09,575] {base.py:68} INFO - Using connection ID 'tutorial_pg_conn' for task execution.
[2022-05-27 08:19:09,577] {python.py:173} INFO - Done. Returned value was: 1
[2022-05-27 08:19:09,593] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=Etl, task_id=merge_data, execution_date=20220526T000000, start_date=20220527T081909, end_date=20220527T081909
[2022-05-27 08:19:09,632] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-27 08:19:09,650] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
